### ISSUE TITLE
train_dialogue_transformer报错

### ISSUE THREAD

**Issue by tao2years** [xiaoxiong74/rasa_chatbot#4]
ValueError: Dimensions must be equal, but are 24 and 23 for 'position__embedding_1/add' (op: 'Add') with input shapes: [?,5,24], [?,5,23].

**Comment by xiaoxiong74** [comment]
@598807302 
在policy/attention_keras 中要求输入的特征是偶数个，即mobile_domain.yml的特征数据量，若报错删除一个或增加一个特征即可

**Comment by tao2years** [comment]
> @598807302
> 在policy/attention_keras 中要求输入的特征是偶数个，即mobile_domain.yml的特征数据量，若报错删除一个或增加一个特征即可

感谢 解决了
